//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ccConfig.rc
//
#define ID_LOAD                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CCCONFIG_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_PAGE_OPTION                 129
#define IDD_PAGE_LOGGING                130
#define IDD_PAGE_OPTION2                131
#define IDD_PAGE_OPTION3                132
#define IDD_PAGE_OPTION4                133
#define IDR_MENU_FILE                   134
#define IDR_MENU_OPEN                   134
#define IDC_TABSHEET                    1000
#define IDC_CHECK_DEBT_DEBUG            1001
#define IDC_CHECK_REPORT_RESULTS_IMMEDIATELY 1001
#define IDC_CHECK_WORK_FETCH_DEBUG      1002
#define ID_SAVE                         1002
#define IDC_CHECK_ABORT_JOBS_ON_EXIT    1002
#define IDC_CHECK_TASK                  1003
#define ID_DELETE                       1003
#define IDC_CHECK_ALLOW_MULTIPLE_CLIENTS 1003
#define IDC_CHECK_FILE_XFER             1004
#define IDC_CHECK_ALLOW_REMOTE_GUI_RPC  1004
#define IDC_EDIT_ALT_PLATFORM           1004
#define IDC_CHECK_SCHED_OPS             1005
#define IDC_CHECK_DISABLE_ATTACH        1005
#define IDC_EDIT_EXCLUSIVE_APP          1005
#define IDC_CHECK_APP_MSG_RECEIVE       1006
#define IDC_CHECK_DONT_CHECK_FILE_SIZES 1006
#define IDC_EDIT_EXCLUSIVE_GPU_APP      1006
#define IDC_CHECK_APP_MSG_SEND          1007
#define IDC_CHECK_DONT_CONTACT_REF_SITE 1007
#define IDC_EDIT_CLIENT_DOWNLOAD_URL    1007
#define IDC_EDIT_HTTP_USER_PASSWD       1007
#define IDC_CHECK_BENCHMARK_DEBUG       1008
#define IDC_CHECK_EXIT_WHEN_IDLE        1008
#define IDC_EDIT_CLIENT_VERSION_CHECK_URL 1008
#define IDC_EDIT_SOCKS_VERSION          1008
#define IDC_CHECK_CHECKPOINT_DEBUG      1009
#define IDC_CHECK_FETCH_MINIMAL_WORK    1009
#define IDC_EDIT_NETWORK_TEST_URL       1009
#define IDC_EDIT_SOCKS_SERVER_NAME      1009
#define IDC_CHECK_COPROC_DEBUG          1010
#define IDC_CHECK_HTTP_1_0              1010
#define IDC_CMB_FORCE_AUTH              1010
#define IDC_CHECK_CPU_SCHED             1011
#define IDC_CHECK_NO_ALT_PLATFORM       1011
#define IDC_EDIT_IGNORE_ATI_DEV         1011
#define IDC_CHECK_CPU_SCHED_DEBUG       1012
#define IDC_CHECK_NO_GPUS               1012
#define IDC_EDIT_IGNORE_CUDA_DEV        1012
#define IDC_EDIT_HTTP_SERVER_NAME       1012
#define IDC_CHECK_DCF_DEBUG             1013
#define IDC_CHECK_NO_PRIORITY_CHANGE    1013
#define IDC_EDIT_MAX_FILE_XFERS         1013
#define IDC_EDIT_SOCKS_SERVER_PORT      1013
#define IDC_CHECK_FILE_XFER_DEBUG       1014
#define IDC_CHECK_OS_RANDOM_ONLY        1014
#define IDC_EDIT_MAX_FILE_XFERS_PER_PROJECT 1014
#define IDC_EDIT_SOCK5_USER_NAME        1014
#define IDC_CHECK_GUI_RPC_DEBUG         1015
#define IDC_CHECK_RUN_APPS_MANUALLY     1015
#define IDC_EDIT_MAX_STDERR_FILE_SIZE   1015
#define IDC_EDIT_SOCKS5_USER_PASSWD     1015
#define IDC_CHECK_HTTP_DEBUG            1016
#define IDC_CHECK_SIMPLE_GUI_ONLY       1016
#define IDC_EDIT_MAX_STDOUT_FILE_SIZE   1016
#define IDC_EDIT_NO_PROXY               1016
#define IDC_CHECK_HTTP_XFER_DEBUG       1017
#define IDC_CHECK_SUPRESS_NET_INFO      1017
#define IDC_EDIT_MAX_TASKS_REPORTED     1017
#define IDC_EDIT_HTTP_SERVER_PORT       1017
#define IDC_CHECK_MEM_USAGE_DEBUG       1018
#define IDC_CHECK_USE_ALL_GPUS          1018
#define IDC_EDIT_NCPUS                  1018
#define IDC_EDIT_HTTP_USER_NAME         1018
#define IDC_CHECK_NETWORK_STATUS_DEBUG  1019
#define IDC_CHECK_USE_CERTS             1019
#define IDC_EDIT_SAVE_STATS_DAYS        1019
#define ID_HELP_E                       1019
#define IDC_CHECK_POLL_DEBUG            1020
#define IDC_CHECK_USE_CERTS_ONLY        1020
#define IDC_EDIT_START_DELAY            1020
#define IDC_SPLIT_OPEN                  1020
#define IDC_CHECK_PROXY_DEBUG           1021
#define IDC_CHECK_ZERO_DEBTS            1021
#define IDC_CHECK_RR_SIMULATION         1022
#define IDC_CHECK_SCHED_OP_DEBUG        1023
#define IDC_CHECK_SCRSAVE_DEBUG         1024
#define IDC_CHECK_STATE_DEBUG           1025
#define IDC_CHECK_STATEFILE_DEBUG       1026
#define IDC_CHECK_TASK_DEBUG            1027
#define IDC_CHECK_TIME_DEBUG            1028
#define IDC_CHECK_TIME_DEBUG2           1029
#define IDC_CHECK_UNPARSED_XML          1029
#define ID_OPEN_OPEN                    32771
#define ID_OPEN_RECENTFILES             32772
#define CRecentFileList                 32773
#define ID_OPEN_RECENTFILES32774        32774
#define ID_RECENTFILES_NONE             32775
#define ID_OPEN_RECENTFILES32776        32776
#define ID_HELP2                        57671
#define ID_HELP_C                       57671

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
